<?php
session_start();
require '../config.php';
require('../TCPDF-main/tcpdf.php');

if (!isset($_SESSION['student_id'])) {
    exit("Unauthorized access");
}

$student_id = $_SESSION['student_id'];
$student_name = $_SESSION['student_name'];

$student_email = mysqli_fetch_assoc(mysqli_query($conn, "SELECT email FROM users WHERE id = $student_id"))['email'];
$course_id = $_GET['course_id'] ?? 0;

$course_data = mysqli_fetch_assoc(mysqli_query($conn, "SELECT title FROM courses WHERE id = $course_id"));
$course_title = $course_data['title'] ?? 'Unknown Course';

// ✅ Store the certificate in DB if not already exists
$check = mysqli_query($conn, "
    SELECT id FROM certificates 
    WHERE user_id = $student_id AND course_id = $course_id
");

if (mysqli_num_rows($check) == 0) {
    $insert = $conn->prepare("
    INSERT INTO certificates (user_id, student_id, course_id, issued_at, certificate_file)
    VALUES (?, ?, ?, NOW(), ?)
");
$filename = "certificate_{$student_id}_{$course_id}_" . time() . ".pdf";
$insert->bind_param("iiis", $student_id, $student_id, $course_id, $filename);
$insert->execute();
}

// ✅ Generate certificate PDF
$pdf = new TCPDF('L', PDF_UNIT, 'A4', true, 'UTF-8', false);
$pdf->SetCreator('MOOCs Platform');
$pdf->SetAuthor('MOOCs Admin');
$pdf->SetTitle('Certificate of Completion');
$pdf->SetMargins(20, 20, 20);
$pdf->SetAutoPageBreak(false, 0); // Disable auto page break to ensure one page

$pdf->AddPage();

// Background rectangle
$pdf->SetFillColor(255, 255, 255);
$pdf->Rect(10, 10, 277, 190, 'F'); // full A4 landscape inner box

// Title
$pdf->SetFont('helvetica', 'B', 28);
$pdf->SetTextColor(0, 102, 204);
$pdf->Cell(0, 20, 'Certificate of Completion', 0, 1, 'C');

// Subtitle
$pdf->Ln(10);
$pdf->SetFont('helvetica', '', 16);
$pdf->SetTextColor(0, 0, 0);
$pdf->Cell(0, 10, "This is to certify that", 0, 1, 'C');

// Student Name
$pdf->Ln(5);
$pdf->SetFont('helvetica', 'B', 22);
$pdf->SetTextColor(0, 51, 102);
$pdf->Cell(0, 12, $student_name, 0, 1, 'C');

// Course Title
$pdf->Ln(5);
$pdf->SetFont('helvetica', '', 16);
$pdf->SetTextColor(0, 0, 0);
$pdf->Cell(0, 10, "has successfully completed the course", 0, 1, 'C');

$pdf->Ln(5);
$pdf->SetFont('helvetica', 'B', 20);
$pdf->SetTextColor(0, 102, 51);
$pdf->Cell(0, 10, $course_title, 0, 1, 'C');

// Date
$pdf->Ln(10);
$pdf->SetFont('helvetica', '', 14);
$pdf->SetTextColor(0, 0, 0);
$pdf->Cell(0, 10, "Awarded on " . date("F j, Y"), 0, 1, 'C');

// Stamp (Platform Verified)
$pdf->SetXY(220, 150); // bottom-right corner
$pdf->SetFont('helvetica', 'B', 12);
$pdf->SetTextColor(0, 102, 204);
$pdf->Cell(50, 10, '✔ MOOCs Verified', 1, 0, 'C');

// Footer Branding
$pdf->SetY(-20);
$pdf->SetFont('helvetica', 'I', 10);
$pdf->SetTextColor(120, 120, 120);
$pdf->Cell(0, 10, 'Generated by MOOCs Learning Platform | www.moocsplatform.com', 0, 0, 'C');

$pdf->Output("Certificate_{$student_name}_{$course_id}.pdf", 'I');
